services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 8079:6379
  ahoy-chat:
    image: ahoy-chat:latest
    container_name: ahoy-chat
    ports:
      - 8080:4444
    depends_on:
      - redis